[package]
name = "rustytracer"
version = "0.1.0"
authors = ["Ryan Glusic <glusic@uwp.edu>"]
edition = "2018"

[dependencies]
cgmath = "0.16.1"
rand = "0.4.3"
image = "0.20.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
erased-serde = "0.3"

[profile.release]
debug = true